// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "rescript/lib/es6/caml_array.js";

function langDocBase(lang) {
  if (lang) {
    return "docs-cn";
  } else {
    return "docs";
  }
}

function whichLang(url) {
  if (url.base.length === 0) {
    return /* English */0;
  }
  var match = Caml_array.get(url.base, 0);
  if (match === "docs-cn") {
    return /* Chinese */1;
  } else {
    return /* English */0;
  }
}

export {
  langDocBase ,
  whichLang ,
}
/* No side effect */
