// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_array from "rescript/lib/es6/caml_array.js";

function langDocBase(lang) {
  switch (lang) {
    case /* English */0 :
        return "docs";
    case /* Chinese */1 :
        return "docs-cn";
    case /* Korean */2 :
        return "docs-ko";
    
  }
}

function whichLang(url) {
  if (url.base.length === 0) {
    return /* English */0;
  }
  var match = Caml_array.get(url.base, 0);
  switch (match) {
    case "docs-cn" :
        return /* Chinese */1;
    case "docs-ko" :
        return /* Korean */2;
    default:
      return /* English */0;
  }
}

export {
  langDocBase ,
  whichLang ,
}
/* No side effect */
