// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as LangUtil from "../common/LangUtil.mjs";
import * as ApiLayout from "./ApiLayout.mjs";
import * as ApiMarkdown from "../components/ApiMarkdown.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function categoriesOf(lang) {
  var docPath = LangUtil.langDocBase(lang);
  return [
          {
            name: "Introduction",
            items: [{
                name: "Overview",
                href: "/" + docPath + "/manual/latest/api"
              }]
          },
          {
            name: "Modules",
            items: [
              {
                name: "Js Module",
                href: "/" + docPath + "/manual/latest/api/js"
              },
              {
                name: "Belt Stdlib",
                href: "/" + docPath + "/manual/latest/api/belt"
              },
              {
                name: "Dom Module",
                href: "/" + docPath + "/manual/latest/api/dom"
              }
            ]
          }
        ];
}

function ApiOverviewLayout$Docs(Props) {
  var langOpt = Props.lang;
  var componentsOpt = Props.components;
  var children = Props.children;
  var lang = langOpt !== undefined ? langOpt : /* English */0;
  var components = componentsOpt !== undefined ? Caml_option.valFromOption(componentsOpt) : ApiMarkdown.$$default;
  var categories = categoriesOf(lang);
  return React.createElement(ApiLayout.make, {
              categories: categories,
              title: "API",
              version: "latest",
              components: components,
              children: children
            });
}

var Docs = {
  make: ApiOverviewLayout$Docs
};

export {
  Docs ,
}
/* react Not a pure module */
